apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-app
spec:
  replicas: 3  # 생성할 Pod의 수 (필요에 맞게 변경)
  selector:
    matchLabels:
      app: efs-app
  template:
    metadata:
      labels:
        app: efs-app
    spec:
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - mountPath: "/data"
          name: efs-storage
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc