apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: irsa
spec:
  serviceAccountName: my-serviceaccount-for-pod
  containers:
    - name: aws-cli
      image: 'amazon/aws-cli:latest'
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
