apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-no-serviceaccount
  namespace: irsa
spec:
  containers:
    - name: aws-cli
      image: 'amazon/aws-cli:latest'
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
