apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      nodePort: 31111
      port: 80
      targetPort: 80


      