apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-pod-no-serviceaccount
  namespace: pod-identity
spec:
  containers:
    - name: aws-cli-pod-no-serviceaccount
      image: 'amazon/aws-cli:latest'
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
