apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-pod
  namespace: pod-identity
spec:
  serviceAccountName: my-serviceaccount-for-pod
  containers:
    - name: aws-cli-pod
      image: 'amazon/aws-cli:latest'
      command:
        - sleep
        - '3600'
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

